enable:

run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocognit
    - gocyclo
    - gofmt
    # - gofumpt
    - goimports
    # - golint
    - goprintffuncname
    # - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll
    - misspell
    - nakedret
    # - rowserrcheck
    - staticcheck
    # - structcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  goconst:
    ignore-tests: false
    min-len: 5
    min-occurrences: 5
  gocyclo:
    min-complexity: 20
  golint:
    ignore-tests: false
    min-confidence: 3
  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx
  gocritic:
    enabled-checks:
      - appendassign
      - appendcombine
      - badcond
      - badregexp
      - boolexprsimplify
      - builtinshadow
      - builtinshadowdecl
      - captlocal
      - caseorder
      - codegencomment
      # - commentedoutcode
      - commentedoutimport
      - commentformatting
      - defaultcaseorder
      - deferinloop
      - deprecatedcomment
      - docstub
      - dupbranchbody
      - dupcase
      - dupimport
      - dupsubexpr
      - elseif
      - emptyfallthrough
      - evalorder
      - exitafterdefer
      - filepathjoin
      - flagname
      - hexliteral
      - hugeparam
      - ifelsechain
      - importshadow
      - initclause
      - mapkey
      - methodexprcall
      - nestingreduce
      - newderef
      - nilvalreturn
      - octalliteral
      - paramtypecombine
      - ptrtorefparam
      - rangeexprcopy
      - rangevalcopy
      - regexppattern
      - regexpsimplify
      - ruleguard
      - singlecaseswitch
      - sloppyreassign
      - sloppytypeassert
      - sortslice
      - sqlquery
      - todocommentwithoutdetail
      - toomanyresultschecker
      - truncatecmp
      - typeassertchain
      - typedeffirst
      - typeswitchvar
      - typeunparen
      - underef
      - unlabelstmt
      - unlambda
      - unnamedresult
      - unnecessaryblock
      - unnecessarydefer
      - weakcond
    settings:
      ruleguard:
        rules: "internal/ruleguard/rules.go"

issues:
  exclude:
    - "(func|method|type|var|struct field|func parameter|method parameter) [^ ]+ should be .*"
  # new: true
  # new-from-rev: v0.0.3
